### ISSUE TITLE
Category 3.3

### ISSUE THREAD

**Issue by Fibrolan** [jobisoft/CategoryManager#34] opened 2019-09-22 16:33 UTC
Hi,

I am using Thunderbird 68.1 with Category 3.3 and I have tested all addons under thurderbird and it seems that Category 3.3 is slowing down the address book terribly. any thought on fixing this ?

Robert

**Comment by jobisoft** [comment] 2019-09-22 18:32
Yeah, I noticed that to, probably the new subcategory feature is causing this. Looking into it this week.

**Comment by Fibrolan** [comment] 2019-09-26 02:35
Good evening!
I was wondering, when you do the modification of it is possible to add a 
feature that works allow you to export the categories along when you export 
your address book as a csv?

Best Regards,


Robert Lichtenstein
President
275 York Hill Blvd
Thornhill, Ontario L4J 3L5
Phone ->905-669-6613 x2001
Fax ->905-669-6614
Email ->robert@bsdnetworks.com
Web ->www.bsdnetworks.com
Skype -> robert_bsd

**Comment by jobisoft** [comment] 2019-10-04 14:23
@Fibrolan 1 : I identified the issue: The calculation of the category sizes takes ages. This is a quickfix, where I just return 0 and skip the size calc. So CatMan no longer slows down TB.

Can you confirm that? I will of course fix the real issue, but that might need some time.

*REMOVED FILE* (Please see comment below with final fix)

-------------------------

@Fibrolan 2 : CatMan comes with a powerful import/export feature around categories:

![grafik](https://user-images.githubusercontent.com/5830621/66214812-b8cd0a80-e6c2-11e9-8c03-ce944b1edd38.png)

**Comment by jobisoft** [comment] 2019-10-04 20:23
I think it is now fixed for good. Can you test and provide feedback? 

[CatMan_3.5.zip](https://github.com/jobisoft/CategoryManager/files/3692195/CatMan-beta.zip)

You can install the file in the AddOn Manager as is, no need to rename it to xpi (which is just a zip anyway).

FYI: THis was caused by the new sub category feature:

![grafik](https://user-images.githubusercontent.com/5830621/66237438-5a6d4f80-e6f5-11e9-8a01-799a2d754dbe.png)

**Comment by jobisoft** [comment] 2019-10-05 06:31
3.5 has been released on ATN.

**Closed as completed by jobisoft** 2019-10-05 06:31 UTC
