### ISSUE TITLE
[gContactSync] category manager upgrade

### ISSUE THREAD

**Issue by kromzatura** [jobisoft/CategoryManager#12] opened 2016-11-02 10:19 UTC
Hallo Admin

i moved from old version to new Catagorymanager2.
all my previous categories which i worked with does not show up now.

to rework all again seems too much for me. 

what might be a problem and how can i i solve it?

thanks for comments.

**Comment by jobisoft** [comment] 2016-11-02 19:24
From the top of my head, I do not know what might have caused this. What is your environment? CardDAV addressbook or local addressbook?

**Comment by kromzatura** [comment] 2016-11-03 09:38
HI John

so hereby whole picture.
work pc. I updated already Thunderbird plugin to category.manager2
made a sync through gcontactsync

at home pc
Thunderbird with plugin catergorymanager2 and gcontactsync
all synced
contacts in
but categories are empty.

how can i make my categories same as on work pc?

2016-11-02 20:24 GMT+01:00 John Bieling notifications@github.com:

**Comment by kromzatura** [comment] 2016-11-03 09:39
its local address book

2016-11-02 20:24 GMT+01:00 John Bieling notifications@github.com:

**Comment by jobisoft** [comment] 2016-11-03 19:05
Ok, this is what i understood:

On your work pc:
1. categories are still there
2. you use gcontactsync to sync google contacts with a local thunderbird address book "local google"
3. you used category manager to add categories to that "local google" address book

On your home pc:
1. you setup your home pc as your work pc, but after syncing your google contacts into a local thunderbird address book, the categories do not show up

Is that correct?

Am 03.11.16 um 10:38 schrieb kromzatura

**Comment by kromzatura** [comment] 2016-11-03 19:08
Yes You are absolutely right

четверг, 3 ноября 2016 г. пользователь John Bieling написал:

**Comment by jobisoft** [comment] 2016-11-03 19:49
There is no easy fix to this. 

It looks like gContactSync is not syncing the "Categories" field from your work pc to the google cloud. Therefore, the online google contacts do not contain any of your category information (they are only stored in your work thunderbird address book).

Consequently, the categories do not show up, after syncing your contacts from google onto another thunderbird installation.

You may ask the developer of gContactSync, if it is possible to sync the "Categories" field as well, but i do not now if this is possible at all ( google must support/allow that )

A dirty workaround would be, to export the thunderbird address book from your work pc and import it on your home pc. Category Manager 2.04 supports this: right click on the "All" entry in the category list and select import/export. A backup of your contacts including your categories might be a good idea anyhow.

There is nothing I could do to fix this ...

Am 03.11.16 um 20:08 schrieb kromzatura

**Comment by jobisoft** [comment] 2017-03-25 09:41
I close this one, because it is a duplicate of #15

**Closed as completed by jobisoft** 2017-03-25 09:41 UTC
Labels: duplicate
